### ISSUE TITLE
drag and drog causes page redirect

### ISSUE THREAD

**Issue by mzelina** [ledsun/redmine_wiki_page_tree#1]
When I drag and drop an item in Firefox 57.0.4, it redirects the browser to a file:/// version of the page which is not found of course.

For example, I have a page called Level_Two. When I drag and drop that onto the Wiki page it redirects to this URL:

file:///projects/mbconfig/wiki/Level_Two

Note that the re-parenting occurs correctly - if I reload the Wiki page the page has indeed moved. It just should not do the redirect.

**Comment by mzelina** [comment]
This patch applied on the 3.4 redmine will prevent the page redirect issue.

```
diff --git a/redmine_wiki_page_tree/assets/javascripts/sidebar__page-tree.js b/redmine_wiki_page_tree/assets/javascripts/sidebar__page-tree.js
index b01e559..d8b1d1e 100644
--- a/redmine_wiki_page_tree/assets/javascripts/sidebar__page-tree.js
+++ b/redmine_wiki_page_tree/assets/javascripts/sidebar__page-tree.js
@@ -11,6 +11,7 @@ document.addEventListener('DOMContentLoaded', () => {
       })
       // ドラッグ時の処理
       a.addEventListener('drop', (e) => {
+       e.preventDefault();
         const url = e.dataTransfer.getData('url') // 移動するwikiページのURL
         const parentId = e.target.getAttribute('data-wiki-page-id') // 親ページのID

```

**Comment by ledsun** [comment]
Thank you for your patch and I fixed this issue!
