### ISSUE TITLE
support jquery-treeview?

### ISSUE THREAD

**Issue by kay54068** [ledsun/redmine_wiki_page_tree#2]
Can support the jquery-treeview?
![圖片](https://user-images.githubusercontent.com/3054544/59446850-dab13180-8e34-11e9-92b3-1c4bc1f0ec53.png)

info:
https://github.com/jzaefferer/jquery-treeview
https://github.com/basyura/redmine_wiki_index_tree_view

**Comment by ledsun** [comment]
I have not used jquery-treeview.
What are the good things about using jquery-treeview?
