### ISSUE TITLE
Is not Redmine 5 compadible

### ISSUE THREAD

**Issue by Adi-18** [ledsun/redmine_wiki_page_tree#3]
As title says

**Comment by ledsun** [comment]
Not sure about Redmine 6. However, I have confirmed that this plugin does not work in Redmine 5.
I think #4 fixes it.
You can try it if you like.

**Comment by Adi-18** [comment]
Yes, I mean RM 5

**Comment by Adi-18** [comment]
Thank you. The fix solved the issue.
